apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigo-frontend
  namespace: sigo-ms
  labels:
    name: sigo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: sigo-frontend
  template:
    metadata:
      labels:
        name: sigo-frontend
    spec:
      containers:
        - name: sigo-frontend
          imagePullPolicy: Always
          image: juniormichieletto/sigo-frontend:latest
          resources:
            requests:
              memory: "10Mi"
            limits:
              memory: "100Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sigo-frontend
  namespace: sigo-ms
spec:
  type: ClusterIP
  selector:
      name: sigo-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sigo-frontend
  namespace: sigo-ms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sigo-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 50Mi
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 2
        periodSeconds: 20
