name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install and npm run build
      run: |
        npm i
        npm run build:prod

    - name: Build container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: juniormichieletto/sigo-frontend:latest
