name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install and npm run build
      run: |
        npm i
        npm run build:prod

    - name: Build container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: juniormichieletto/sigo-frontend:latest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Install digitalocean doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Push to Docker Hub
      run: docker push juniormichieletto/sigo-frontend:latest

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 sigo-tcc-k8s-cluster

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f ./k8s/deployment.yml
